sudo: required
language: node_js
node_js:
  - "lts/*"
services:
  - docker

before_install:
  - docker build -t terranup16/udemy-fib-react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run terranup16/udemy-fib-react-test npm test

after_success:
  - docker build -t terranup16/udemy-fib-client ./client
  - docker build -t terranup16/udemy-fib-nginx ./nginx
  - docker build -t terranup16/udemy-fib-server ./server
  - docker build -t terranup16/udemy-fib-worker ./worker
  # Login to the Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to Docker Hub
  - docker push terranup16/udemy-fib-client
  - docker push terranup16/udemy-fib-nginx
  - docker push terranup16/udemy-fib-server
  - docker push terranup16/udemy-fib-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-887143717967
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"